const roleListObject = {
  dateStamp: "29/11/2021 14:29:01",
  roleData: [
    { roleTitle: "3D CAD Technician", category: "man" },
    { roleTitle: "Additive Manufacturing Engineer", category: "man" },
    { roleTitle: "AI/ML Developer", category: "ai" },
    { roleTitle: "AI/ML Expert", category: "ai" },
    { roleTitle: "AI/ML Lead", category: "ai" },
    { roleTitle: "API Developer", category: "sw" },
    { roleTitle: "Applied AI/ML Advisor", category: "ai" },
    { roleTitle: "Backend Developer", category: "sw" },
    { roleTitle: "Backend Development Lead", category: "sw" },
    { roleTitle: "Banking Expert", category: "fin" },
    { roleTitle: "Biocompatibility Testing", category: "med" },
    { roleTitle: "Bioinformatics Developer", category: "med" },
    { roleTitle: "Biomedical Application Advisor", category: "med" },
    { roleTitle: "Biotechnology Research Scientist", category: "med" },
    { roleTitle: "Blockchain Developer", category: "dlt" },
    { roleTitle: "Blockchain/DLT Architect", category: "dlt" },
    { roleTitle: "Browser Embedded Developer", category: "sw" },
    {
      roleTitle: "Business Development and Market Engagement",
      category: "gen",
    },
    {
      roleTitle: "Business Development and Regulatory Affairs",
      category: "gen",
    },
    { roleTitle: "Business Model Development", category: "gen" },
    { roleTitle: "CAD Engine Developer", category: "man" },
    { roleTitle: "CE and Standards", category: "man" },
    { roleTitle: "Clinical Compliance", category: "med" },
    { roleTitle: "Clinical Lead", category: "med" },
    { roleTitle: "Compliance", category: "gen" },
    { roleTitle: "Computer Graphics Developer", category: "sw" },
    { roleTitle: "Computer Vision Engineer", category: "vis" },
    { roleTitle: "COVID-19 Safety-testing", category: "cov" },
    { roleTitle: "Cryptography and Security Researcher", category: "sw" },
    { roleTitle: "Data Analyst", category: "dat" },
    { roleTitle: "Data Architect", category: "dat" },
    { roleTitle: "Data Architecture Lead", category: "dat" },
    { roleTitle: "Data Science Lead", category: "dat" },
    { roleTitle: "Data Scientist", category: "dat" },
    { roleTitle: "Database Developer", category: "sw" },
    { roleTitle: "Design Engineer", category: "man" },
    { roleTitle: "DLT Security Auditor", category: "dlt" },
    { roleTitle: "Electrical Designer", category: "man" },
    { roleTitle: "Electrical Engineer", category: "man" },
    { roleTitle: "Electromechanical Engineer", category: "man" },
    { roleTitle: "Electronics Engineer", category: "man" },
    { roleTitle: "Electronics prototyping", category: "man" },
    { roleTitle: "Encryption Developer", category: "sw" },
    { roleTitle: "Exploitation and Market Engagement", category: "gen" },
    { roleTitle: "Firmware Engineer", category: "man" },
    { roleTitle: "Frontend and Backend Tester", category: "sw" },
    { roleTitle: "Frontend Developer", category: "sw" },
    { roleTitle: "Frontend Development Lead", category: "sw" },
    { roleTitle: "Full stack Developer", category: "sw" },
    { roleTitle: "Fundamental Algorithm Developer", category: "sw" },
    { roleTitle: "Gamification Developer", category: "sw" },
    { roleTitle: "Graph Database Developer", category: "sw" },
    { roleTitle: "Hardware Designer", category: "man" },
    { roleTitle: "Hardware Engineer", category: "man" },
    { roleTitle: "Hardware Lead", category: "man" },
    { roleTitle: "Hardware Prototyping", category: "man" },
    { roleTitle: "Heuristic Optimisation Developer", category: "ai" },
    { roleTitle: "Industrial Design", category: "man" },
    { roleTitle: "iOS/Android Developer", category: "sw" },
    { roleTitle: "IP Manager", category: "gen" },
    { roleTitle: "Javascript Developer", category: "sw" },
    { roleTitle: "LCA Analyst", category: "gen" },
    { roleTitle: "Legal Advisor", category: "gen" },
    { roleTitle: "Manufacturer", category: "man" },
    { roleTitle: "Market Engagement", category: "gen" },
    { roleTitle: "Mechanical Engineer", category: "man" },
    { roleTitle: "Medical Expert", category: "med" },
    { roleTitle: "Medical Lead", category: "med" },
    { roleTitle: "Mobile Application Developer", category: "sw" },
    { roleTitle: "Networking Developer", category: "sw" },
    { roleTitle: "Neural Network Developer", category: "ai" },
    { roleTitle: "Neural Network Lead", category: "ai" },
    { roleTitle: "Neuroscientist", category: "med" },
    { roleTitle: "NLP Developer", category: "nlp" },
    { roleTitle: "Penetration Tester", category: "sw" },
    { roleTitle: "Product Designer", category: "man" },
    { roleTitle: "Production Engineer", category: "man" },
    { roleTitle: "Project Manager", category: "gen" },
    { roleTitle: "Prototyping", category: "gen" },
    { roleTitle: "Prototyping", category: "man" },
    { roleTitle: "Radiologist", category: "med" },
    { roleTitle: "Rapid Prototying Engineer", category: "man" },
    { roleTitle: "Regulatory Framework Advisor", category: "gen" },
    { roleTitle: "Security Developer", category: "sw" },
    { roleTitle: "Senior Backend Developer", category: "sw" },
    { roleTitle: "Senior Electrical engineer", category: "man" },
    { roleTitle: "Senior Electronics Engineer", category: "man" },
    { roleTitle: "Senior Frontend Developer", category: "sw" },
    { roleTitle: "Senior Full Stack Developer", category: "sw" },
    { roleTitle: "Senior Mechanical Engineer", category: "man" },
    { roleTitle: "Senior ML Research Scientist", category: "ai" },
    { roleTitle: "Senior Software Developer", category: "sw" },
    { roleTitle: "Sensor Developer", category: "man" },
    { roleTitle: "Soft Computing Developer", category: "ai" },
    { roleTitle: "Software Developer", category: "sw" },
    { roleTitle: "Software Development Lead", category: "sw" },
    { roleTitle: "Sustainability Analyst", category: "gen" },
    { roleTitle: "Technical Design Authority", category: "gen" },
    { roleTitle: "Technical Lead", category: "gen" },
    { roleTitle: "Testing Engineer", category: "gen" },
    { roleTitle: "Trial Manager", category: "gen" },
    { roleTitle: "User Experience Designer", category: "ui" },
    { roleTitle: "User Experience Developer", category: "ui" },
    { roleTitle: "User Experience Lead", category: "ui" },
    { roleTitle: "User Testing", category: "gen" },
    { roleTitle: "Validation", category: "gen" },
    { roleTitle: "Verification", category: "gen" },
  ],
};

const taskListObject = {
  dateStamp: "09/12/2021 17:28:47",
  taskData: [
    {
      taskTitle: "Account Compliance (KYC, AML)",
      category: "fin",
      taskType: "Finance Sector",
      taskId: "1",
    },
    {
      taskTitle: "Agile Sprint Planning",
      category: "gen",
      taskType: "Project Management",
      taskId: "2",
    },
    {
      taskTitle: "AI/ML Training ",
      category: "ai",
      taskType: "Artificial Intelligence",
      taskId: "3",
    },
    {
      taskTitle: "Algorithm Development and Refinement",
      category: "gen",
      taskType: "General",
      taskId: "4",
    },
    {
      taskTitle: "Android and iOS Development",
      category: "sw",
      taskType: "Software",
      taskId: "5",
    },
    {
      taskTitle: "API Development",
      category: "sw",
      taskType: "Software",
      taskId: "6",
    },
    {
      taskTitle: "Architecture Design",
      category: "sw",
      taskType: "Software",
      taskId: "7",
    },
    {
      taskTitle: "Automated Data Import",
      category: "dat",
      taskType: "Data Science",
      taskId: "8",
    },
    {
      taskTitle: "Backend Development",
      category: "sw",
      taskType: "Software",
      taskId: "9",
    },
    {
      taskTitle: "Baseline Sustainability Assessment",
      category: "sus",
      taskType: "Sustainability",
      taskId: "10",
    },
    {
      taskTitle: "Benefit Assessment",
      category: "gen",
      taskType: "General",
      taskId: "11",
    },
    {
      taskTitle: "Biometrics (fingerprint, Facial Recognition) Integration",
      category: "sw",
      taskType: "Software",
      taskId: "12",
    },
    {
      taskTitle: "Bug Fixing and Optimisation",
      category: "gen",
      taskType: "General",
      taskId: "13",
    },
    {
      taskTitle: "Business and Product-market Fit Analysis",
      category: "gen",
      taskType: "Exploitation",
      taskId: "14",
    },
    {
      taskTitle: "Business Model Development",
      category: "gen",
      taskType: "Exploitation",
      taskId: "15",
    },
    {
      taskTitle: "Care Pathway Analysis",
      category: "med",
      taskType: "Medical",
      taskId: "16",
    },
    {
      taskTitle: "Classification",
      category: "ai",
      taskType: "Artificial Intelligence",
      taskId: "17",
    },
    {
      taskTitle: "Clinical Data Analysis",
      category: "med",
      taskType: "Medical",
      taskId: "18",
    },
    {
      taskTitle: "Clinician User Testing",
      category: "med",
      taskType: "Medical",
      taskId: "19",
    },
    {
      taskTitle: "Clustering",
      category: "ai",
      taskType: "Artificial Intelligence",
      taskId: "20",
    },
    {
      taskTitle: "CNN Training",
      category: "ai",
      taskType: "Artificial Intelligence",
      taskId: "21",
    },
    {
      taskTitle: "Compliance",
      category: "fin",
      taskType: "Finance Sector",
      taskId: "22",
    },
    {
      taskTitle: "Connectors to Slack, MS Office, Google Docs etc",
      category: "sw",
      taskType: "Software",
      taskId: "23",
    },
    {
      taskTitle: "Continuous Dialogue with Regulators",
      category: "gen",
      taskType: "General",
      taskId: "24",
    },
    {
      taskTitle: "Continuous Dialogue with Stakeholders",
      category: "gen",
      taskType: "Exploitation",
      taskId: "25",
    },
    {
      taskTitle: "Continuous Integration",
      category: "gen",
      taskType: "General",
      taskId: "26",
    },
    {
      taskTitle: "Continuous Market Appraisal",
      category: "gen",
      taskType: "Exploitation",
      taskId: "27",
    },
    {
      taskTitle: "Continuous Risk Appraisal",
      category: "gen",
      taskType: "Project Management",
      taskId: "28",
    },
    {
      taskTitle: "Core Architecture",
      category: "sw",
      taskType: "Software",
      taskId: "29",
    },
    {
      taskTitle: "Core Data Platform Development",
      category: "dat",
      taskType: "Data Science",
      taskId: "30",
    },
    {
      taskTitle: "Core Platform Development",
      category: "gen",
      taskType: "General",
      taskId: "31",
    },
    {
      taskTitle: "Cross Platform Compatibility",
      category: "sw",
      taskType: "Software",
      taskId: "32",
    },
    {
      taskTitle: "Cryptography Research",
      category: "sw",
      taskType: "Software",
      taskId: "33",
    },
    {
      taskTitle: "Customer and Stakeholder Workshops for User Feedback",
      category: "gen",
      taskType: "Exploitation",
      taskId: "34",
    },
    {
      taskTitle: "Data Aggregation and Display",
      category: "dat",
      taskType: "Data Science",
      taskId: "35",
    },
    {
      taskTitle: "Data analysis and interpretation",
      category: "dat",
      taskType: "Data Science",
      taskId: "36",
    },
    {
      taskTitle: "Data Analysis, Corealation and Hypothesis Design",
      category: "dat",
      taskType: "Data Science",
      taskId: "37",
    },
    {
      taskTitle: "Data architecture and modelling",
      category: "dat",
      taskType: "Data Science",
      taskId: "38",
    },
    {
      taskTitle: "Data Capture, Import and Storage (ETL)",
      category: "dat",
      taskType: "Data Science",
      taskId: "39",
    },
    {
      taskTitle: "Data Collection, Cleansing and Normalisation System",
      category: "dat",
      taskType: "Data Science",
      taskId: "40",
    },
    {
      taskTitle: "Data Dashboard",
      category: "dat",
      taskType: "Data Science",
      taskId: "41",
    },
    {
      taskTitle: "Data Import, Cleansing, Harmonisation and Standardisation",
      category: "dat",
      taskType: "Data Science",
      taskId: "42",
    },
    {
      taskTitle: "Data Model Caching and Lambda",
      category: "dat",
      taskType: "Data Science",
      taskId: "43",
    },
    {
      taskTitle: "Data Security & Encryption",
      category: "dat",
      taskType: "Data Science",
      taskId: "44",
    },
    {
      taskTitle: "Data security (encryption etc)",
      category: "dat",
      taskType: "Data Science",
      taskId: "45",
    },
    {
      taskTitle: "Data Visualisation UI",
      category: "dat",
      taskType: "Data Science",
      taskId: "46",
    },
    {
      taskTitle: "Database and Backend Design",
      category: "sw",
      taskType: "Software",
      taskId: "47",
    },
    {
      taskTitle: "Deep Learning System",
      category: "ai",
      taskType: "Artificial Intelligence",
      taskId: "48",
    },
    {
      taskTitle: "Destructive Testing",
      category: "man",
      taskType: "Hardware",
      taskId: "49",
    },
    {
      taskTitle: "Dissemination Events (for disseminating research outputs)",
      category: "gen",
      taskType: "Exploitation",
      taskId: "50",
    },
    {
      taskTitle:
        "Distributed Cloud Platform Deployment and Multi/Micro Service Architecture",
      category: "sw",
      taskType: "Software",
      taskId: "51",
    },
    {
      taskTitle: "DLT Model Architecture",
      category: "dlt",
      taskType: "Distributed Ledger",
      taskId: "52",
    },
    {
      taskTitle: "Efficient Data Retrieval from Graph Database",
      category: "sw",
      taskType: "Software",
      taskId: "53",
    },
    {
      taskTitle: "Electronics Design ",
      category: "man",
      taskType: "Hardware",
      taskId: "54",
    },
    {
      taskTitle: "Embedded Software Development",
      category: "sw",
      taskType: "Software",
      taskId: "55",
    },
    {
      taskTitle: "Encryption & Security",
      category: "sw",
      taskType: "Software",
      taskId: "56",
    },
    {
      taskTitle: "Engage Open Banking Initiative",
      category: "fin",
      taskType: "Finance Sector",
      taskId: "57",
    },
    {
      taskTitle: "Environment Proofing (Water etc)",
      category: "man",
      taskType: "Hardware",
      taskId: "58",
    },
    {
      taskTitle: "Environmental & Social Impact Report",
      category: "sus",
      taskType: "Sustainability",
      taskId: "59",
    },
    {
      taskTitle: "Environmental Impact Modelling",
      category: "sus",
      taskType: "Sustainability",
      taskId: "60",
    },
    {
      taskTitle: "Establishing UX Features for Implementation",
      category: "ui",
      taskType: "User Experience",
      taskId: "61",
    },
    {
      taskTitle: "Ethics Approval for Clinical Study",
      category: "med",
      taskType: "Medical",
      taskId: "62",
    },
    {
      taskTitle: "Exploitation and Market Engagement",
      category: "gen",
      taskType: "Exploitation",
      taskId: "63",
    },
    {
      taskTitle: "Exploitation Planning",
      category: "gen",
      taskType: "Exploitation",
      taskId: "64",
    },
    {
      taskTitle: "Feature extraction module",
      category: "ai",
      taskType: "Artificial Intelligence",
      taskId: "65",
    },
    {
      taskTitle: "Finance Industry Requirements",
      category: "fin",
      taskType: "Finance Sector",
      taskId: "66",
    },
    {
      taskTitle: "Functional & Performance testing",
      category: "gen",
      taskType: "Testing",
      taskId: "67",
    },
    {
      taskTitle: "Functional and Technical Specification",
      category: "gen",
      taskType: "General",
      taskId: "68",
    },
    {
      taskTitle: "Functional/performance Testing",
      category: "gen",
      taskType: "Testing",
      taskId: "69",
    },
    {
      taskTitle: "Gamification",
      category: "sw",
      taskType: "Software",
      taskId: "70",
    },
    {
      taskTitle: "Graph Database Architecture",
      category: "sw",
      taskType: "Software",
      taskId: "71",
    },
    {
      taskTitle: "Hardware & Firmware Sensor Incorporation",
      category: "man",
      taskType: "Hardware",
      taskId: "72",
    },
    {
      taskTitle: "Health Economics Study",
      category: "med",
      taskType: "Medical",
      taskId: "73",
    },
    {
      taskTitle: "Impact Assessment",
      category: "gen",
      taskType: "General",
      taskId: "74",
    },
    {
      taskTitle: "Import of Data from Distributed Ledgers",
      category: "dlt",
      taskType: "Distributed Ledger",
      taskId: "75",
    },
    {
      taskTitle: "Installation, Maintenance and Quality Control Procedures",
      category: "man",
      taskType: "Hardware",
      taskId: "76",
    },
    {
      taskTitle: "Integration, Optimisation and Testing",
      category: "gen",
      taskType: "General",
      taskId: "77",
    },
    {
      taskTitle: "Intelligent Web Data Harvesting System",
      category: "dat",
      taskType: "Data Science",
      taskId: "78",
    },
    {
      taskTitle: "IP Audit and Protection",
      category: "gen",
      taskType: "Exploitation",
      taskId: "79",
    },
    {
      taskTitle: "KYC and AML Technologies",
      category: "fin",
      taskType: "Finance Sector",
      taskId: "80",
    },
    {
      taskTitle: "Leading AI and Machine Learning strategies",
      category: "ai",
      taskType: "Artificial Intelligence",
      taskId: "81",
    },
    {
      taskTitle: "Legal Aspects (IP Ownership, Data Protection)",
      category: "gen",
      taskType: "General",
      taskId: "82",
    },
    {
      taskTitle: "Legal Compliance & Security",
      category: "gen",
      taskType: "General",
      taskId: "83",
    },
    {
      taskTitle: "Legal Requirements (SLAs, Compliance, Auditing)",
      category: "gen",
      taskType: "General",
      taskId: "84",
    },
    {
      taskTitle: "Life Cycle Analysis (LCA)",
      category: "sus",
      taskType: "Sustainability",
      taskId: "85",
    },
    {
      taskTitle: "Light-weighting Development",
      category: "man",
      taskType: "Hardware",
      taskId: "86",
    },
    {
      taskTitle: "Machine Learning",
      category: "ai",
      taskType: "Artificial Intelligence",
      taskId: "87",
    },
    {
      taskTitle: "Machine Learning Architecture",
      category: "ai",
      taskType: "Artificial Intelligence",
      taskId: "88",
    },
    {
      taskTitle: "Machine Learning systems (Supervised and unsupervised)",
      category: "ai",
      taskType: "Artificial Intelligence",
      taskId: "89",
    },
    {
      taskTitle: "Machine Learning Training",
      category: "ai",
      taskType: "Artificial Intelligence",
      taskId: "90",
    },
    {
      taskTitle: "Market Analysis and Business Use Cases",
      category: "gen",
      taskType: "Exploitation",
      taskId: "91",
    },
    {
      taskTitle: "Market Appraisal",
      category: "gen",
      taskType: "Exploitation",
      taskId: "92",
    },
    {
      taskTitle: "Market Engagement",
      category: "gen",
      taskType: "Exploitation",
      taskId: "93",
    },
    {
      taskTitle: "Market Research",
      category: "gen",
      taskType: "Exploitation",
      taskId: "94",
    },
    {
      taskTitle: "Material Research",
      category: "man",
      taskType: "Hardware",
      taskId: "95",
    },
    {
      taskTitle: "Model Development and Training",
      category: "ai",
      taskType: "Artificial Intelligence",
      taskId: "96",
    },
    {
      taskTitle: "Model Optimisation & Implementation",
      category: "dat",
      taskType: "Data Science",
      taskId: "97",
    },
    {
      taskTitle: "Model Testing and Optimisation",
      category: "dat",
      taskType: "Data Science",
      taskId: "98",
    },
    {
      taskTitle: "Modular AI system Development",
      category: "ai",
      taskType: "Artificial Intelligence",
      taskId: "99",
    },
    {
      taskTitle: "Monthly and Quarterly Progress Meetings",
      category: "gen",
      taskType: "Project Management",
      taskId: "100",
    },
    {
      taskTitle: "Multi-Objective Optimisation",
      category: "ai",
      taskType: "Artificial Intelligence",
      taskId: "101",
    },
    {
      taskTitle: "Natural Language Processing",
      category: "nlp",
      taskType: "Artificial Intelligence",
      taskId: "102",
    },
    {
      taskTitle: "Neural Network Architecture",
      category: "ai",
      taskType: "Artificial Intelligence",
      taskId: "103",
    },
    {
      taskTitle: "Neural Network Training",
      category: "ai",
      taskType: "Artificial Intelligence",
      taskId: "104",
    },
    {
      taskTitle: "NLP Model Architecture",
      category: "nlp",
      taskType: "Artificial Intelligence",
      taskId: "105",
    },
    {
      taskTitle: "Ongoing Clinical Literature Review",
      category: "med",
      taskType: "Medical",
      taskId: "106",
    },
    {
      taskTitle: "Open Rest API",
      category: "sw",
      taskType: "Software",
      taskId: "107",
    },
    {
      taskTitle: "Open REST API Development",
      category: "sw",
      taskType: "Software",
      taskId: "108",
    },
    {
      taskTitle: "Optimisation",
      category: "gen",
      taskType: "General",
      taskId: "109",
    },
    {
      taskTitle: "Output Processing and Optimisation",
      category: "ai",
      taskType: "Artificial Intelligence",
      taskId: "110",
    },
    {
      taskTitle: "Parallel Computing (Using GPUs)",
      category: "sw",
      taskType: "Software",
      taskId: "111",
    },
    {
      taskTitle: "Penetration (security) Testing",
      category: "gen",
      taskType: "Testing",
      taskId: "112",
    },
    {
      taskTitle: "Performance Evaluation and Benchmarking",
      category: "gen",
      taskType: "Testing",
      taskId: "113",
    },
    {
      taskTitle: "Performance Optimisation",
      category: "gen",
      taskType: "General",
      taskId: "114",
    },
    {
      taskTitle: "Platform Architecture Design",
      category: "sw",
      taskType: "Software",
      taskId: "115",
    },
    {
      taskTitle: "Platform Development",
      category: "sw",
      taskType: "Software",
      taskId: "116",
    },
    {
      taskTitle: "Population Cluster & Regression Analyses ",
      category: "ai",
      taskType: "Artificial Intelligence",
      taskId: "117",
    },
    {
      taskTitle: "Power and Battery development",
      category: "man",
      taskType: "Hardware",
      taskId: "118",
    },
    {
      taskTitle: "Pricing/Payment Modules",
      category: "gen",
      taskType: "General",
      taskId: "119",
    },
    {
      taskTitle: "Processing Data from Distributed Ledgers",
      category: "dlt",
      taskType: "Distributed Ledger",
      taskId: "120",
    },
    {
      taskTitle: "Project Management",
      category: "gen",
      taskType: "Project Management",
      taskId: "121",
    },
    {
      taskTitle: "Prototype Development",
      category: "gen",
      taskType: "General",
      taskId: "122",
    },
    {
      taskTitle: "Prototyping",
      category: "gen",
      taskType: "General",
      taskId: "123",
    },
    {
      taskTitle: "Prototyping, Testing and Optimisation",
      category: "gen",
      taskType: "General",
      taskId: "124",
    },
    {
      taskTitle: "Purchase, Licensing and Payment System",
      category: "gen",
      taskType: "General",
      taskId: "125",
    },
    {
      taskTitle: "Real Time Data Ingestion",
      category: "dat",
      taskType: "Data Science",
      taskId: "126",
    },
    {
      taskTitle: "Real-time Analytics and Data Visualisation System",
      category: "dat",
      taskType: "Data Science",
      taskId: "127",
    },
    {
      taskTitle: "Real-time Analytics and Insights",
      category: "dat",
      taskType: "Data Science",
      taskId: "128",
    },
    {
      taskTitle: "Regulatory/Compliance",
      category: "gen",
      taskType: "General",
      taskId: "129",
    },
    {
      taskTitle: "Reporting",
      category: "gen",
      taskType: "Project Management",
      taskId: "130",
    },
    {
      taskTitle: "Risk Appraisal",
      category: "gen",
      taskType: "Project Management",
      taskId: "131",
    },
    {
      taskTitle: "Safety, Privacy, Legal & Regulations",
      category: "gen",
      taskType: "General",
      taskId: "132",
    },
    {
      taskTitle: "Scalable Platform Architecture",
      category: "sw",
      taskType: "Software",
      taskId: "133",
    },
    {
      taskTitle: "Security (authentication/validation) and Data Recovery",
      category: "sw",
      taskType: "Software",
      taskId: "134",
    },
    {
      taskTitle: "Security Testing",
      category: "gen",
      taskType: "Testing",
      taskId: "135",
    },
    {
      taskTitle: "Security/Penetration Testing",
      category: "gen",
      taskType: "Testing",
      taskId: "136",
    },
    {
      taskTitle: "Sensor Hardware Development",
      category: "man",
      taskType: "Hardware",
      taskId: "137",
    },
    {
      taskTitle: "Smart Contract Development",
      category: "dlt",
      taskType: "Distributed Ledger",
      taskId: "138",
    },
    {
      taskTitle: "Software Architecture Definition",
      category: "sw",
      taskType: "Software",
      taskId: "139",
    },
    {
      taskTitle: "Stakeholder Workshops",
      category: "gen",
      taskType: "Exploitation",
      taskId: "140",
    },
    {
      taskTitle: "Standards and Regulation",
      category: "gen",
      taskType: "General",
      taskId: "141",
    },
    {
      taskTitle: "State-of-Art Review",
      category: "gen",
      taskType: "General",
      taskId: "142",
    },
    {
      taskTitle: "System Architecture",
      category: "gen",
      taskType: "General",
      taskId: "143",
    },
    {
      taskTitle: "Testing and Iterative Improvement",
      category: "gen",
      taskType: "Testing",
      taskId: "144",
    },
    {
      taskTitle: "Third Party Requirements",
      category: "gen",
      taskType: "General",
      taskId: "145",
    },
    {
      taskTitle: "UI/UX Development",
      category: "ui",
      taskType: "User Experience",
      taskId: "146",
    },
    {
      taskTitle: "Unstructured Data Storage Format",
      category: "dat",
      taskType: "Data Science",
      taskId: "147",
    },
    {
      taskTitle: "User Cases",
      category: "gen",
      taskType: "General",
      taskId: "148",
    },
    {
      taskTitle: "User Interface Development",
      category: "ui",
      taskType: "User Experience",
      taskId: "149",
    },
    {
      taskTitle: "User Testing",
      category: "gen",
      taskType: "Testing",
      taskId: "150",
    },
    {
      taskTitle: "Validation and Compliance",
      category: "gen",
      taskType: "Testing",
      taskId: "151",
    },
    {
      taskTitle: "Visual Analytics",
      category: "dat",
      taskType: "Data Science",
      taskId: "152",
    },
  ],
};
const riskTemplateObject = {
  dateStamp: "29/11/2021 14:29:01",
  riskData: [
    {
      riskId: "man1",
      riskType: "managerial",
      category: "gen",
      riskDescription:
        "Project documentation/evidence is inadequate resulting in project delays",
      riskPreProbability: 2,
      riskPreConsequence: 2,
      riskMitigation:
        "Continuous assessment and action plan for the documentation/evidence gathered during project to avoid delays",
      riskPostProbability: 2,
      riskPostConsequence: 2,
    },
    {
      riskId: "man2",
      riskType: "managerial",
      category: "gen",
      riskDescription:
        "Resources required to meet technical needs exceed expectation",
      riskPreProbability: 2,
      riskPreConsequence: 2,
      riskMitigation:
        "Project Manager will continually assess tasks and resources. Continuous effort on recruitment using existing networks will prevent delays in project delivery",
      riskPostProbability: 2,
      riskPostConsequence: 2,
    },
    {
      riskId: "man3",
      riskType: "managerial",
      category: "gen",
      riskDescription: "Misinterpretation leads to technical errors",
      riskPreProbability: 2,
      riskPreConsequence: 2,
      riskMitigation:
        "Agile development means that issues will be found quickly and rectified. Monthly project progress meetings and online space for documents will ensure technical information is clear/accessible",
      riskPostProbability: 2,
      riskPostConsequence: 2,
    },
    {
      riskId: "man4",
      riskType: "managerial",
      category: "gen",
      riskDescription: "Key team member incapacitated",
      riskPreProbability: 2,
      riskPreConsequence: 2,
      riskMitigation:
        "Standards and progress reports will ensure smooth handover. Regular team feedback ensures PM understands progress. Learning points are captured in a team wiki, which allows for fast knowledge transfer",
      riskPostProbability: 2,
      riskPostConsequence: 2,
    },
    {
      riskId: "man5",
      riskType: "managerial",
      category: "gen",
      riskDescription:
        "Insufficient resourcing of the new members of the team compromises the ability to deliver project",
      riskPreProbability: 2,
      riskPreConsequence: 2,
      riskMitigation:
        "All key members of the team already sourced. Team members are committed to the project through supportive company culture and robust project/performance management structures",
      riskPostProbability: 2,
      riskPostConsequence: 2,
    },
    {
      riskId: "man6",
      riskType: "managerial",
      category: "gen",
      riskDescription: "Changing requirements or scope creep delay development",
      riskPreProbability: 2,
      riskPreConsequence: 2,
      riskMitigation:
        "Agile methodologies and milestones to fence requirements. Management will encourage an open and transparent development environment that helps identify delays",
      riskPostProbability: 2,
      riskPostConsequence: 2,
    },
    {
      riskId: "man7",
      riskType: "managerial",
      category: "gen",
      riskDescription: "Key team member incapacitated",
      riskPreProbability: 2,
      riskPreConsequence: 2,
      riskMitigation:
        "Standards and progress reports will ensure smooth handover. Regular team feedback ensures PM understands progress. Learning points are captured in a team wiki, which allows for fast knowledge transfer",
      riskPostProbability: 2,
      riskPostConsequence: 2,
    },
    {
      riskId: "man8",
      riskType: "managerial",
      category: "gen",
      riskDescription:
        "Unable to recruit to fill team gaps from known contacts",
      riskPreProbability: 2,
      riskPreConsequence: 2,
      riskMitigation:
        "Team has extensive experienced in recruitment. Initial, confidential discussions with several potential candidates, who have expressed interest but cannot confirm until project finance is secured. Project has been planned with roles involving these people",
      riskPostProbability: 2,
      riskPostConsequence: 2,
    },
    {
      riskId: "man9",
      riskType: "managerial",
      category: "gen",
      riskDescription:
        "Development team are too distracted with project and development of core business is neglected",
      riskPreProbability: 2,
      riskPreConsequence: 2,
      riskMitigation:
        "Monthly board meetings to ensure strategy delivers business plan. Independent chairman and investor director",
      riskPostProbability: 2,
      riskPostConsequence: 2,
    },
    {
      riskId: "man10",
      riskType: "managerial",
      category: "cov",
      riskDescription:
        "Key team member becomes incapacitated due to COVID-19 or other illness",
      riskPreProbability: 2,
      riskPreConsequence: 2,
      riskMitigation:
        "Scrum-based agile software development planning and management with overlapping tasks to remove key person risk. Standards and progress reports will ensure smooth handover",
      riskPostProbability: 2,
      riskPostConsequence: 2,
    },
    {
      riskId: "man11",
      riskType: "managerial",
      category: "cov",
      riskDescription:
        "COVID-19 Lockdowns continue intermittantly through project",
      riskPreProbability: 2,
      riskPreConsequence: 2,
      riskMitigation:
        "Team will remain flexible in work schedule. Project timelines can move accordingly if facilities access becomes restricted or suppliers experience delays",
      riskPostProbability: 2,
      riskPostConsequence: 2,
    },
    {
      riskId: "man12",
      riskType: "managerial",
      category: "col",
      riskDescription:
        "Complex and large consortium cannot be managed effectively",
      riskPreProbability: 2,
      riskPreConsequence: 2,
      riskMitigation:
        "Use of Comms/chat tools (MS Teams etc). Effective meeting management. Advance planning to manage availability. Clear roles, accountabilities and decision-making mechanisms",
      riskPostProbability: 2,
      riskPostConsequence: 2,
    },
    {
      riskId: "man13",
      riskType: "managerial",
      category: "sub",
      riskDescription: "Sub‐contractors fail to meet expectation",
      riskPreProbability: 2,
      riskPreConsequence: 2,
      riskMitigation:
        "Trusted sub‐contractors engaged for project duration. Progress reviewed regularly. Agreed deadlines and penalties",
      riskPostProbability: 2,
      riskPostConsequence: 2,
    },
    {
      riskId: "tech1",
      riskType: "technical",
      category: "gen",
      riskDescription:
        "New disruptive technologies are developed that [company name] does not support quickly enough, making the platform less attractive/scalable",
      riskPreProbability: 2,
      riskPreConsequence: 2,
      riskMitigation:
        "Will ensure coverage of a large range of technologies and constantly expand this list as new technologies are introduced",
      riskPostProbability: 2,
      riskPostConsequence: 2,
    },
    {
      riskId: "tech2",
      riskType: "technical",
      category: "sub",
      riskDescription:
        "Unable to deliver prototype of the system with capabilities as scoped because of technical challenges involved",
      riskPreProbability: 2,
      riskPreConsequence: 2,
      riskMitigation:
        "Company has experience required to complete technical tasks, and has experienced subcontractors. Alternative technologies identified during development using an accelerated evolutionary approach",
      riskPostProbability: 2,
      riskPostConsequence: 2,
    },
    {
      riskId: "tech3",
      riskType: "technical",
      category: "man",
      riskDescription:
        "Manufacturing system is not as scalable as required by business model",
      riskPreProbability: 2,
      riskPreConsequence: 2,
      riskMitigation:
        "Team will apply its experience and knowledge of developing scalable manufacturing systems using modular architecture to allow rapid scaling. Optimising processes and working with manufacturing partners to ensure scalable production. Extensive performance/scalability testing with supply‐chain and market throughout development",
      riskPostProbability: 2,
      riskPostConsequence: 2,
    },
    {
      riskId: "tech4",
      riskType: "technical",
      category: "sw",
      riskDescription:
        "Incompatibility of code across different customer/user environments",
      riskPreProbability: 2,
      riskPreConsequence: 2,
      riskMitigation:
        "Regular testing of the compatibility of code between different environments and implementations during development",
      riskPostProbability: 2,
      riskPostConsequence: 2,
    },
    {
      riskId: "tech5",
      riskType: "technical",
      category: "sw",
      riskDescription:
        "Platform unable to scale to cope with the usage and performance required by business model",
      riskPreProbability: 2,
      riskPreConsequence: 2,
      riskMitigation:
        "Elastic cloud-based architecture and exhaustive performance/scalability testing. Initially onboarding organisations with low operational loads. Provisioning of physical hardware if necessary",
      riskPostProbability: 2,
      riskPostConsequence: 2,
    },
    {
      riskId: "tech6",
      riskType: "technical",
      category: "sw",
      riskDescription:
        "Technology stack chosen for development does not meet requirements of prototype",
      riskPreProbability: 2,
      riskPreConsequence: 2,
      riskMitigation:
        "Proactive research of available technologies to ensure required features can be developed. Research will ensure a backup in case any technology fails to meet expectation",
      riskPostProbability: 2,
      riskPostConsequence: 2,
    },
    {
      riskId: "tech7",
      riskType: "technical",
      category: "sw",
      riskDescription: "Level of component reusability not as high as expected",
      riskPreProbability: 2,
      riskPreConsequence: 2,
      riskMitigation:
        "Regular iterative prototyping, active focus on code reuse, active participation of the team in customer-facing integration work across multiple deployments",
      riskPostProbability: 2,
      riskPostConsequence: 2,
    },
    {
      riskId: "tech8",
      riskType: "technical",
      category: "sw",
      riskDescription:
        "Not able to develop full functionality of the platform so impact is more niche than anticipated",
      riskPreProbability: 2,
      riskPreConsequence: 2,
      riskMitigation:
        "Discussion with industry partners to identify priority functionalities. Extensive testing of the platform and comparison to specification to ensure it provides planned functionality",
      riskPostProbability: 2,
      riskPostConsequence: 2,
    },
    {
      riskId: "tech9",
      riskType: "technical",
      category: "sw",
      riskDescription:
        "Specification is incorrect or inflexible, limiting the types of data or modules that can be integrated",
      riskPreProbability: 2,
      riskPreConsequence: 2,
      riskMitigation:
        "Team has extensive experience in developing open and flexible software specifications. Careful specification of the platform at project inception, consulting experts where required",
      riskPostProbability: 2,
      riskPostConsequence: 2,
    },
    {
      riskId: "tech10",
      riskType: "technical",
      category: "sw",
      riskDescription:
        "Components are highly interlinked/interdependent and failure of an individual component results in entire system failure ",
      riskPreProbability: 2,
      riskPreConsequence: 2,
      riskMitigation:
        "Deep testing (including penetrative) in stages: 1) Exhaustive in-house component testing to ensure functionality and security. 2) Sequential component integration and in-house testing to ensure components work together and easily identify flaws. 3) Testing with market partner",
      riskPostProbability: 2,
      riskPostConsequence: 2,
    },
    {
      riskId: "tech11",
      riskType: "technical",
      category: "sw",
      riskDescription:
        "Unable to integrate code (including 3rd parties) into core platform",
      riskPreProbability: 2,
      riskPreConsequence: 2,
      riskMitigation:
        "Minimal use of third party source code. Thorough research of any third party library required and review of licensing to ensure minimal risk to the business model",
      riskPostProbability: 2,
      riskPostConsequence: 2,
    },
    {
      riskId: "tech12",
      riskType: "technical",
      category: "sw",
      riskDescription:
        "Issues with dev environment causes delays in development schedule",
      riskPreProbability: 2,
      riskPreConsequence: 2,
      riskMitigation:
        "Robust dev environment will be built before starting the project. All the required tools will be procured, installed and tested beforehand",
      riskPostProbability: 2,
      riskPostConsequence: 2,
    },
    {
      riskId: "tech13",
      riskType: "technical",
      category: "sw",
      riskDescription:
        "3rd-party dependencies for technology development creates security and licensing issues",
      riskPreProbability: 2,
      riskPreConsequence: 2,
      riskMitigation:
        "Minimal 3rd-party source code usage. Where 3rd-party necessary, library will be thoroughly researched and licensing reviewed. High community usage regularly monitored and releases kept up-to-date. Automated library-patching tools used to rapidly fix any security vulnerabilities",
      riskPostProbability: 2,
      riskPostConsequence: 2,
    },
    {
      riskId: "tech14",
      riskType: "technical",
      category: "sw",
      riskDescription:
        "Loop holes in the source code make it vulnerable to injection of malicious code",
      riskPreProbability: 2,
      riskPreConsequence: 2,
      riskMitigation:
        "Thorough code reviews will be done by senior developers to ensure the code is of the best quality and no loop holes are introduced that makes it vulnerable",
      riskPostProbability: 2,
      riskPostConsequence: 2,
    },
    {
      riskId: "tech15",
      riskType: "technical",
      category: "sw",
      riskDescription:
        "Updates to third-party platforms affect data integration or create compatibility issues",
      riskPreProbability: 2,
      riskPreConsequence: 2,
      riskMitigation:
        "Extensive testing to ensure software is compatible with all platforms. Development team to create & disseminate required software updates",
      riskPostProbability: 2,
      riskPostConsequence: 2,
    },
    {
      riskId: "tech16",
      riskType: "technical",
      category: "sw",
      riskDescription:
        "Users' IT constraints limit product functionality resulting in poor reputation",
      riskPreProbability: 2,
      riskPreConsequence: 2,
      riskMitigation:
        "Thorough research on users' typical IT systems and security measures. R&D for maximum functionality with minimal user IT requirements",
      riskPostProbability: 2,
      riskPostConsequence: 2,
    },
    {
      riskId: "tech17",
      riskType: "technical",
      category: "ui",
      riskDescription:
        "User Interface is not intuitive or responsive, negatively impacting UX",
      riskPreProbability: 2,
      riskPreConsequence: 2,
      riskMitigation:
        "Exhaustive usability testing throughout entire agile scrum development process to incorporate feedback during project and assess best approach. Architecture and technology stack selected for optimal performance on all devices",
      riskPostProbability: 2,
      riskPostConsequence: 2,
    },
    {
      riskId: "tech18",
      riskType: "technical",
      category: "ui",
      riskDescription:
        "Processing requirements mean only a limited feature set can be offered across mobile/tablet devices",
      riskPreProbability: 2,
      riskPreConsequence: 2,
      riskMitigation:
        "Enabling multi-threading on less powerful devices (mobiles, tablets). Developing modular feature set, customised to each device. Releasing mobile/tablet versions as companion apps",
      riskPostProbability: 2,
      riskPostConsequence: 2,
    },
    {
      riskId: "tech19",
      riskType: "technical",
      category: "ui",
      riskDescription:
        "Platform cannot offer real-time visualisation impacting user engagement",
      riskPreProbability: 2,
      riskPreConsequence: 2,
      riskMitigation:
        "Team is experienced in developing high performance data capture and visualisation systems. Multiple technologies will be tested during the project using an agile, evolutionary approach",
      riskPostProbability: 2,
      riskPostConsequence: 2,
    },
    {
      riskId: "tech20",
      riskType: "technical",
      category: "ui",
      riskDescription:
        "Response time of real-time platform not adequate for a good UX ",
      riskPreProbability: 2,
      riskPreConsequence: 2,
      riskMitigation:
        "Architecture and technology stack selected for optimal performance on all devices",
      riskPostProbability: 2,
      riskPostConsequence: 2,
    },
    {
      riskId: "tech21",
      riskType: "technical",
      category: "dat",
      riskDescription:
        "Errors in external data input leads to erroneous/misleading data for users",
      riskPreProbability: 2,
      riskPreConsequence: 2,
      riskMitigation:
        "Automated and manual quality/integrity check of external data before use. Working with data providers to address issues in datasets ingested",
      riskPostProbability: 2,
      riskPostConsequence: 2,
    },
    {
      riskId: "tech22",
      riskType: "technical",
      category: "dat",
      riskDescription:
        "Data transmission errors result in wrong data being fed into the analytics engine creating misleading outputs",
      riskPreProbability: 2,
      riskPreConsequence: 2,
      riskMitigation:
        "Data integrity and validity checking mechanism built into the platform to ensure only accurate data is stored in the system for processing and erroneuos data",
      riskPostProbability: 2,
      riskPostConsequence: 2,
    },
    {
      riskId: "tech23",
      riskType: "technical",
      category: "dat",
      riskDescription:
        "Increased data ingested and complex processing requirements affect performance, reducing capability and scalability",
      riskPreProbability: 2,
      riskPreConsequence: 2,
      riskMitigation:
        "Elastic cloud based architecture and exhaustive performance/scalability testing throughout development will ensure platform is fit for purpose. Regular review of technical issues and features that impact scalability. Design and architecture optimised based on priority functionalities. Working with service providers to ensure platform can cope with increased data and performance requirements. Load & stress testing pre-launch. Elastic server architecture and system design allows horizontal scalability (database-as-a-service, distributed data-storage)",
      riskPostProbability: 2,
      riskPostConsequence: 2,
    },
    {
      riskId: "tech24",
      riskType: "technical",
      category: "dat",
      riskDescription:
        "Complex raw datasets cannot be harmonised effectively, reducing comprehensive function of platform",
      riskPreProbability: 2,
      riskPreConsequence: 2,
      riskMitigation:
        "Multiple AI/ML techniques applied. Datasets broken down to core components and combined, according to desired outcome",
      riskPostProbability: 2,
      riskPostConsequence: 2,
    },
    {
      riskId: "tech25",
      riskType: "technical",
      category: "dat",
      riskDescription:
        "Unable to sufficiently automate data cleansing, impacting scalability ",
      riskPreProbability: 2,
      riskPreConsequence: 2,
      riskMitigation:
        "If data cleansing cannot be fully automated, manual intervention will be used to complete the cleansing process",
      riskPostProbability: 2,
      riskPostConsequence: 2,
    },
    {
      riskId: "tech26",
      riskType: "technical",
      category: "dat",
      riskDescription:
        "Unable to develop a universal model that adapts to individual users",
      riskPreProbability: 2,
      riskPreConsequence: 2,
      riskMitigation:
        "Exhaustive usability testing throughout entire agile scrum development process to incorporate feedback during project and assess best approach. Insight from project will serve to work towards personalisation",
      riskPostProbability: 2,
      riskPostConsequence: 2,
    },
    {
      riskId: "tech27",
      riskType: "technical",
      category: "dat",
      riskDescription:
        "Data security breach results in data loss/corruption and loss of IP, affecting credibility and platform function",
      riskPreProbability: 2,
      riskPreConsequence: 2,
      riskMitigation:
        "Regular data security auditing. Static data as well as data transmitted over the network will be encrypted as per industry standards (ISO27001). Appropriate and GDPR compliant data backup mechanisms implemented",
      riskPostProbability: 2,
      riskPostConsequence: 2,
    },
    {
      riskId: "tech28",
      riskType: "technical",
      category: "dat",
      riskDescription:
        "Aggregation and cleaning reveals extensive missing data",
      riskPreProbability: 2,
      riskPreConsequence: 2,
      riskMitigation:
        "Project team will develop algorithms to analyse and fix data. Will work with data providers to ensure only high quality datasets are produced/ingested",
      riskPostProbability: 2,
      riskPostConsequence: 2,
    },
    {
      riskId: "tech29",
      riskType: "technical",
      category: "dat",
      riskDescription:
        "Key data for Data Acquisition Strategy sits with 3rd parties who are unwilling/unable to make it available",
      riskPreProbability: 2,
      riskPreConsequence: 2,
      riskMitigation:
        "Discovery early in project. Work with consortium partners with existing relationships to 3rd party to unblock. Data acquisition expertise to remove technical blockers",
      riskPostProbability: 2,
      riskPostConsequence: 2,
    },
    {
      riskId: "tech30",
      riskType: "technical",
      category: "dat",
      riskDescription:
        "Failure of Cloud based services or external systems leads to platform outage, causing delays and data loss",
      riskPreProbability: 2,
      riskPreConsequence: 2,
      riskMitigation:
        "Close management of service relationships. Communication with service suppliers to maintain awareness of potential service outages. Processes and SLAs developed with third parties to ensure platform runs smoothly",
      riskPostProbability: 2,
      riskPostConsequence: 2,
    },
    {
      riskId: "tech31",
      riskType: "technical",
      category: "dlt",
      riskDescription:
        "Serious programming errors discovered in particular Smart Contracts",
      riskPreProbability: 2,
      riskPreConsequence: 2,
      riskMitigation:
        "Continued assessment and auditing of the code front-end and back-end developer constant communication. Swift action on identifying bugs and solving them. Smart Contracts to be equipped with upgrade capability whenever possible",
      riskPostProbability: 2,
      riskPostConsequence: 2,
    },
    {
      riskId: "tech32",
      riskType: "technical",
      category: "dlt",
      riskDescription:
        "Blockchain forks lead to inconsistent smart contract state or overwritten transactions",
      riskPreProbability: 2,
      riskPreConsequence: 2,
      riskMitigation:
        "Monitoring of blockchain state. Back-end development kept agile. The technical team will set up the project with the capacity to adapt",
      riskPostProbability: 2,
      riskPostConsequence: 2,
    },
    {
      riskId: "tech33",
      riskType: "technical",
      category: "dlt",
      riskDescription:
        "Computational complexity makes platform uneconomical to use in blockchain network where there is a need to pay for processing power",
      riskPreProbability: 2,
      riskPreConsequence: 2,
      riskMitigation:
        "Working with experts to increase efficiency, exploring layer 2 solutions (side-chains, para-chains) and continual assessment of features that impact computational overhead. Release of blockchain updates will help address structural scaling issues",
      riskPostProbability: 2,
      riskPostConsequence: 2,
    },
    {
      riskId: "tech34",
      riskType: "technical",
      category: "dlt",
      riskDescription:
        "Attack on underlying blockchain forces multiple nodes offline, disabling the system",
      riskPreProbability: 2,
      riskPreConsequence: 2,
      riskMitigation:
        "Asynchronous transaction bus ensures stability during increased blockchain latency. Implementing second-layer solutions (side-chains & para-chains) to minimise transactions being forwarded to blockchain",
      riskPostProbability: 2,
      riskPostConsequence: 2,
    },
    {
      riskId: "tech35",
      riskType: "technical",
      category: "dlt",
      riskDescription:
        "Instability of Blockchain nodes prevent relays from functioning correctly",
      riskPreProbability: 2,
      riskPreConsequence: 2,
      riskMitigation:
        "Off-chain pre-validation ensures relayers submit minimal data to the network. Alternative P2P protocol for relayers will synchronise data submission to avoid front-running and reduce need for constant blockchain network synchronisation",
      riskPostProbability: 2,
      riskPostConsequence: 2,
    },
    {
      riskId: "tech36",
      riskType: "technical",
      category: "dlt",
      riskDescription: "Blockchain is not an accepted and trusted technology",
      riskPreProbability: 2,
      riskPreConsequence: 2,
      riskMitigation:
        "Collaboration with blockchain providers to ensure blockchain accepted. Case studies produced to clearly evidence transparent communications, benefits and trust",
      riskPostProbability: 2,
      riskPostConsequence: 2,
    },
    {
      riskId: "tech37",
      riskType: "technical",
      category: "dlt",
      riskDescription:
        "Incorrect information stored on blockchain due to other parts of the platform/system being hacked",
      riskPreProbability: 2,
      riskPreConsequence: 2,
      riskMitigation:
        "Due diligence, minimising personal data on blockchain. Frequent checks to assess information accuracy",
      riskPostProbability: 2,
      riskPostConsequence: 2,
    },
    {
      riskId: "tech38",
      riskType: "technical",
      category: "dlt",
      riskDescription:
        "Technological breakthroughs such as quantum computing or a vulnerability in the public blockchain technology allow Smart Contracts’ ledger to be altered",
      riskPreProbability: 2,
      riskPreConsequence: 2,
      riskMitigation: "Use of private blockchain",
      riskPostProbability: 2,
      riskPostConsequence: 2,
    },
    {
      riskId: "tech39",
      riskType: "technical",
      category: "ai",
      riskDescription:
        "Neural network is unable to forecast more accurately than existing tools, impacting scalability of platform",
      riskPreProbability: 2,
      riskPreConsequence: 2,
      riskMitigation:
        "Model will rely on a range of state-of-art techniques both supervised AI (E.g. neural nets, machine learning, decision trees). The prediction system will use the best predictive model or combination of models. Constant evaluation of architecture to evaluate fit",
      riskPostProbability: 2,
      riskPostConsequence: 2,
    },
    {
      riskId: "tech40",
      riskType: "technical",
      category: "ai",
      riskDescription: "Unable to achieve accurate predictive algorithm",
      riskPreProbability: 2,
      riskPreConsequence: 2,
      riskMitigation:
        "Increasing volume of data used to feed machine learning algorithm by running more projects. Experimenting with different approaches for predictive models (neural networks, decision trees, etc)",
      riskPostProbability: 2,
      riskPostConsequence: 2,
    },
    {
      riskId: "tech41",
      riskType: "technical",
      category: "ai",
      riskDescription:
        "Identifying optimum trade-offs between classification sensitivity/specificity cannot be automated",
      riskPreProbability: 2,
      riskPreConsequence: 2,
      riskMitigation:
        "Combining multiple models and incorporating manual rules where required to find the optimum compromise between sensitivity and specificity",
      riskPostProbability: 2,
      riskPostConsequence: 2,
    },
    {
      riskId: "tech42",
      riskType: "technical",
      category: "ai",
      riskDescription:
        "Training algorithm is not optimised, increasing training time and extending timelines",
      riskPreProbability: 2,
      riskPreConsequence: 2,
      riskMitigation:
        "Main bottleneck expected to be file I/O. If the training code is too slow, team will rep incorporate a caching module to store data on fast-access hardware to significantly increase speed",
      riskPostProbability: 2,
      riskPostConsequence: 2,
    },
    {
      riskId: "tech43",
      riskType: "technical",
      category: "ai",
      riskDescription:
        "Unable to standardise input data sufficiently for algorithm reliability and efficiency",
      riskPreProbability: 2,
      riskPreConsequence: 2,
      riskMitigation:
        "Highly experienced team will improve standardisation via data reclassification and training. Structuring of data and insights should help work towards building working model for trial population, and ensure it can be scalable",
      riskPostProbability: 2,
      riskPostConsequence: 2,
    },
    {
      riskId: "tech44",
      riskType: "technical",
      category: "ai",
      riskDescription: "Post-processing fails to increase system performance",
      riskPreProbability: 2,
      riskPreConsequence: 2,
      riskMitigation:
        "Improving CNN performance to a sufficient level so only minimal post-processing is required. Rapid iteration and continuous testing of post-processing algorithms",
      riskPostProbability: 2,
      riskPostConsequence: 2,
    },
    {
      riskId: "tech45",
      riskType: "technical",
      category: "ai",
      riskDescription:
        "Training data is not sufficient to achieve highly accurate insights",
      riskPreProbability: 2,
      riskPreConsequence: 2,
      riskMitigation:
        "Access to large historical and current datasets to build accurate models. Frequent iteration of models to improve accuracy. Additional data will be gathered direct per customer authorisation (via an integration service and APIs). Multiple data-matching fields used to optimise match-rate likelihoods",
      riskPostProbability: 2,
      riskPostConsequence: 2,
    },
    {
      riskId: "tech46",
      riskType: "technical",
      category: "ai",
      riskDescription:
        "Unable to integrate the multiple forecast and optimisation algorithms required to create complete system",
      riskPreProbability: 2,
      riskPreConsequence: 2,
      riskMitigation:
        "Robust and detailed data integration specification and continuous/exhaustive integration testing for all modules throughout the development cycle",
      riskPostProbability: 2,
      riskPostConsequence: 2,
    },
    {
      riskId: "tech47",
      riskType: "technical",
      category: "ai",
      riskDescription:
        "Optimisation algorithm unable to produce optimal solution rapidly enough to support decision-making",
      riskPreProbability: 2,
      riskPreConsequence: 2,
      riskMitigation:
        "Algorithm will rely on a range of state-of-art optimisation techniques. The optimisation system will use the best or combination of models to achieve required performance",
      riskPostProbability: 2,
      riskPostConsequence: 2,
    },
    {
      riskId: "tech48",
      riskType: "technical",
      category: "ai",
      riskDescription:
        "Quality of signals generated for training predictive model not adequate to generate accurate forecasts/recommendations",
      riskPreProbability: 2,
      riskPreConsequence: 2,
      riskMitigation:
        "Data curated through multiple technology channels (data mining, NLP, ML) to generate highly accurate & structured signal data to train the model",
      riskPostProbability: 2,
      riskPostConsequence: 2,
    },
    {
      riskId: "tech49",
      riskType: "technical",
      category: "ai",
      riskDescription:
        "Model dataset is too small to establish ML and achieve high accuracy",
      riskPreProbability: 2,
      riskPreConsequence: 2,
      riskMitigation:
        "Access to specialists and best practice will help define appropriate model. Focus on the sample population specificities, high quality biometric data and user feedback through continuous integrated development and testing should help identify the key factors relevant for development of a scalable model. Frequent iteration of models to improve accuracy and data structure should help enable identification of core factors which can be generalised to larger groups. Working with large partners, sourcing publicly available information will provide the foundation to move from manual to automated",
      riskPostProbability: 2,
      riskPostConsequence: 2,
    },
    {
      riskId: "tech50",
      riskType: "technical",
      category: "ai",
      riskDescription:
        "Model unable to optimise schedule and suggest improved strategies",
      riskPreProbability: 2,
      riskPreConsequence: 2,
      riskMitigation:
        "Multiple technology paths investigated with regular, early testing to establish best option. Identification of alternative optimisations strategies that do not include rescheduling",
      riskPostProbability: 2,
      riskPostConsequence: 2,
    },
    {
      riskId: "tech51",
      riskType: "technical",
      category: "ai",
      riskDescription:
        "Existing hardware cannot cope with the processing requirements of the system",
      riskPreProbability: 2,
      riskPreConsequence: 2,
      riskMitigation:
        "Cloud based services enable ample access to massive scale computing. New graph optimised processors, designed to speed up machine learning methods, are currrently in development and will be investigated for suitability",
      riskPostProbability: 2,
      riskPostConsequence: 2,
    },
    {
      riskId: "tech52",
      riskType: "technical",
      category: "ai",
      riskDescription: "ML unable to achieve accurate assessment",
      riskPreProbability: 2,
      riskPreConsequence: 2,
      riskMitigation:
        "ML model will rely on multiple state-of-art techniques both supervised AI (including ML decision trees, neural nets) and traditional forecasting. Rigorous testing with stakeholders, validation and continuous monitoring of model performance. Prediction system will use best predictive model or combination of models. Constant evaluation of architecture to evaluate fit",
      riskPostProbability: 2,
      riskPostConsequence: 2,
    },
    {
      riskId: "tech53",
      riskType: "technical",
      category: "ai",
      riskDescription:
        "Not possible to identify a suitable ML algorithm for value regression prediction",
      riskPreProbability: 2,
      riskPreConsequence: 2,
      riskMitigation:
        "Evaluating multiple algorithms to establish strengths, weakness and applicable uses. Thorough journal review to identify new algorithms, use of review papers and conference proceedings. Identification of analogous use-cases in adjacent fields of machine learning",
      riskPostProbability: 2,
      riskPostConsequence: 2,
    },
    {
      riskId: "tech54",
      riskType: "technical",
      category: "nlp",
      riskDescription:
        "Natural Language Processing (NLP) cannot be achieved, or insights are not useful, restricting the effectiveness of the platform",
      riskPreProbability: 2,
      riskPreConsequence: 2,
      riskMitigation:
        "Multiple NLP techniques used to establish the most effective strategy. User-centred development ensures platform meets needs. Regular engagement with clients throughout project helps to identify key usage barriers",
      riskPostProbability: 2,
      riskPostConsequence: 2,
    },
    {
      riskId: "tech55",
      riskType: "technical",
      category: "med",
      riskDescription:
        "Unable to interface with existing NHS systems after project",
      riskPreProbability: 2,
      riskPreConsequence: 2,
      riskMitigation:
        "Close collaboration with partners within NHS and use of third party integration software will ensure that on project completion software will integrate smoothly with existing NHS systems",
      riskPostProbability: 2,
      riskPostConsequence: 2,
    },
    {
      riskId: "leg1",
      riskType: "legal",
      category: "gen",
      riskDescription: "Users are unsatisfied with performance and litigate",
      riskPreProbability: 2,
      riskPreConsequence: 2,
      riskMitigation:
        "T&Cs will clearly disclaim liability for performance as actions out of company’s control",
      riskPostProbability: 2,
      riskPostConsequence: 2,
    },
    {
      riskId: "leg2",
      riskType: "legal",
      category: "gen",
      riskDescription: "Regulation is too burdensome",
      riskPreProbability: 2,
      riskPreConsequence: 2,
      riskMitigation:
        "Communication with relevant regulatory bodies to receive updates about changes in regulations impacting development. Legal team experts advising on each change and the impact on the business",
      riskPostProbability: 2,
      riskPostConsequence: 2,
    },
    {
      riskId: "leg3",
      riskType: "legal",
      category: "gen",
      riskDescription:
        "Brexit changes market structures and exposes company to regulatory changes that limit service provision",
      riskPreProbability: 2,
      riskPreConsequence: 2,
      riskMitigation:
        "Advanced scenario planning and extensive market liaison to limit risk and maximise potential",
      riskPostProbability: 2,
      riskPostConsequence: 2,
    },
    {
      riskId: "leg4",
      riskType: "legal",
      category: "man",
      riskDescription:
        "Malfunctioning of the platform results in an accident causing injury",
      riskPreProbability: 2,
      riskPreConsequence: 2,
      riskMitigation:
        "Project plan ensures exhaustive testing for fail-safe product aspects. Appropriate disclaimers put in place by company lawyers",
      riskPostProbability: 2,
      riskPostConsequence: 2,
    },
    {
      riskId: "leg5",
      riskType: "legal",
      category: "sw",
      riskDescription:
        "Incorrect T&Cs do not protect customer IP, limiting engagement with the platform",
      riskPreProbability: 2,
      riskPreConsequence: 2,
      riskMitigation:
        "Legal experts will draft appropriate T&Cs in discussion with customers and partners",
      riskPostProbability: 2,
      riskPostConsequence: 2,
    },
    {
      riskId: "leg6",
      riskType: "legal",
      category: "dlt",
      riskDescription: "Errors in Smart Contract result in litigation",
      riskPreProbability: 2,
      riskPreConsequence: 2,
      riskMitigation:
        "Thorough analysis of contracts before deployment as templates will mitigate the risks of errors that could lead to litigation. Appropriate legal contracts in place",
      riskPostProbability: 2,
      riskPostConsequence: 2,
    },
    {
      riskId: "leg7",
      riskType: "legal",
      category: "dat",
      riskDescription: "Data protection and privacy issues",
      riskPreProbability: 2,
      riskPreConsequence: 2,
      riskMitigation: "Appropriate legal contracts in place",
      riskPostProbability: 2,
      riskPostConsequence: 2,
    },
    {
      riskId: "leg8",
      riskType: "legal",
      category: "dat",
      riskDescription:
        "Company releases inferred company specific transaction data, contravening regulations (GDPR etc)",
      riskPreProbability: 2,
      riskPreConsequence: 2,
      riskMitigation:
        "Strict control of data permissions. Careful development and regular testing of APIs to ensure all data provided in anonymise",
      riskPostProbability: 2,
      riskPostConsequence: 2,
    },
    {
      riskId: "leg9",
      riskType: "legal",
      category: "med",
      riskDescription:
        "Unable to gain ethics approval in time for clinical testing",
      riskPreProbability: 2,
      riskPreConsequence: 2,
      riskMitigation:
        "Ethics approval documentation from project start (well in advance of clinical trial) and regular contact with approval authority",
      riskPostProbability: 2,
      riskPostConsequence: 2,
    },
    {
      riskId: "leg10",
      riskType: "legal",
      category: "med",
      riskDescription: "Unable to achieve regulatory approval",
      riskPreProbability: 2,
      riskPreConsequence: 2,
      riskMitigation:
        "Close collaboration with expert subcontractor to validate system. Continuous dialogue with international regulators to allow a smooth approvals process",
      riskPostProbability: 2,
      riskPostConsequence: 2,
    },
    {
      riskId: "env1",
      riskType: "environmental",
      category: "man",
      riskDescription: "Resulting Embodied Energy per device is considerable",
      riskPreProbability: 2,
      riskPreConsequence: 2,
      riskMitigation:
        "Environmental assessment will reveal issues. Existing and proposed environmental and safety legislation and guidance reviewed",
      riskPostProbability: 2,
      riskPostConsequence: 2,
    },
    {
      riskId: "env2",
      riskType: "environmental",
      category: "gen",
      riskDescription:
        "Lifecycle environmental impacts exceed acceptable limits",
      riskPreProbability: 2,
      riskPreConsequence: 2,
      riskMitigation:
        "Professional environmental assessment to reveal issues and focus R&D. Existing and proposed environmental, industry and safety legislation and guidance regularly reviewed",
      riskPostProbability: 2,
      riskPostConsequence: 2,
    },
    {
      riskId: "env3",
      riskType: "environmental",
      category: "dat",
      riskDescription:
        "Increased volume of cloud storage and processing requirements significantly increase system's carbon emissions",
      riskPreProbability: 2,
      riskPreConsequence: 2,
      riskMitigation:
        "All data‐storage and processing for system will use cloud servers powered using renewable energy",
      riskPostProbability: 2,
      riskPostConsequence: 2,
    },
    {
      riskId: "com1",
      riskType: "commercial",
      category: "gen",
      riskDescription:
        "Project results do not convince investors of adequate RoI to raise sufficient commercialisation capital",
      riskPreProbability: 2,
      riskPreConsequence: 2,
      riskMitigation:
        "Will ensure company is positioned correctly to achieve funding. Continual RoI assessment will quantify market benefits and provide robust RoI evidence. Project completion will reduce risks and make company more attractive to investors",
      riskPostProbability: 2,
      riskPostConsequence: 2,
    },
    {
      riskId: "com2",
      riskType: "commercial",
      category: "gen",
      riskDescription: "Unable to achieve market recognition and protect IP",
      riskPreProbability: 2,
      riskPreConsequence: 2,
      riskMitigation:
        "R&D in conjunction with stakeholders to establish market trust and recognition. IP protection initiated and will be updated where required by technical developments. Extensive communications around initial pilots to gain maximum visibility. Participation in industry conferences and events as speakers",
      riskPostProbability: 2,
      riskPostConsequence: 2,
    },
    {
      riskId: "com3",
      riskType: "commercial",
      category: "gen",
      riskDescription:
        "Company is accused of IP infringement and does not have the resources to challenge action",
      riskPreProbability: 2,
      riskPreConsequence: 2,
      riskMitigation:
        "IP searches already carried out and show Freedom to Operate. Investigating IP infringement insurance",
      riskPostProbability: 2,
      riskPostConsequence: 2,
    },
    {
      riskId: "com4",
      riskType: "commercial",
      category: "gen",
      riskDescription:
        "Rivals reverse engineer or develop similar technological solution",
      riskPreProbability: 2,
      riskPreConsequence: 2,
      riskMitigation:
        "Monitoring international competitive landscape and adjusting strategy. Project allows faster evolution of the platform to stay ahead of rivals. IP protection initiated and will be updated where required by technical developments in collaboration with IP lawyers",
      riskPostProbability: 2,
      riskPostConsequence: 2,
    },
    {
      riskId: "com5",
      riskType: "commercial",
      category: "gen",
      riskDescription:
        "Business model developed for technology is not viable and team is unable to monetise it",
      riskPreProbability: 2,
      riskPreConsequence: 2,
      riskMitigation:
        "Model tested early and regular market engagement to appraise features. Continued development and iteration as required to ensure it can be monetised",
      riskPostProbability: 2,
      riskPostConsequence: 2,
    },
    {
      riskId: "com6",
      riskType: "commercial",
      category: "gen",
      riskDescription:
        "Business model and selling price is not suitable for a disruptive market-entry",
      riskPreProbability: 2,
      riskPreConsequence: 2,
      riskMitigation:
        "In-depth market analysis, with regular market engagement and model tested early to appraise and validate features. Continued development as required to ensure it can be monetised",
      riskPostProbability: 2,
      riskPostConsequence: 2,
    },
    {
      riskId: "com7",
      riskType: "commercial",
      category: "gen",
      riskDescription:
        "Unable to create a product that is commercially valid within target market",
      riskPreProbability: 2,
      riskPreConsequence: 2,
      riskMitigation:
        "Market appraisal and engagement throughout project. Regular appraisal of features throughout project",
      riskPostProbability: 2,
      riskPostConsequence: 2,
    },
    {
      riskId: "com8",
      riskType: "commercial",
      category: "gen",
      riskDescription: "Customers do not trust the technology",
      riskPreProbability: 2,
      riskPreConsequence: 2,
      riskMitigation:
        "Providing incentives for initial adoption (free trials etc) and targeting based on propensity to utilise the technology. Leveraging existing network and affinity group distribution channels to develop trust, build knowledge and inform product development",
      riskPostProbability: 2,
      riskPostConsequence: 2,
    },
    {
      riskId: "com9",
      riskType: "commercial",
      category: "gen",
      riskDescription:
        "New disruptive technologies are developed that company does not support quickly enough, making the platform less attractive/scalable",
      riskPreProbability: 2,
      riskPreConsequence: 2,
      riskMitigation:
        "Will ensure coverage of a large range of technologies and constantly expand this list as new technologies are introduced",
      riskPostProbability: 2,
      riskPostConsequence: 2,
    },
    {
      riskId: "com10",
      riskType: "commercial",
      category: "gen",
      riskDescription: "Customers do not understand USP offered",
      riskPreProbability: 2,
      riskPreConsequence: 2,
      riskMitigation:
        "Pre-launch research of target users and A-B testing of language to describe innovative product and branding to ensure product launch success",
      riskPostProbability: 2,
      riskPostConsequence: 2,
    },
    {
      riskId: "com11",
      riskType: "commercial",
      category: "gen",
      riskDescription:
        "Cashflow constraints due to quarterly-in-arrears grant payments delay project progress",
      riskPreProbability: 2,
      riskPreConsequence: 2,
      riskMitigation:
        "Match-funding payment schedule has been agreed to ensure adequate cashflow and contingency at all times",
      riskPostProbability: 2,
      riskPostConsequence: 2,
    },
    {
      riskId: "com12",
      riskType: "commercial",
      category: "gen",
      riskDescription: "Unable to convince customers to use the platform",
      riskPreProbability: 2,
      riskPreConsequence: 2,
      riskMitigation:
        "Continual dialogue with potential customers to ensure product/platform meets their needs. Developing case studies demonstrating impact and benefits during project. Healthy pipeline of customers waiting to engage",
      riskPostProbability: 2,
      riskPostConsequence: 2,
    },
    {
      riskId: "com13",
      riskType: "commercial",
      category: "cov",
      riskDescription:
        "COVID‐19 safety concerns prevent product being adopted by market",
      riskPreProbability: 2,
      riskPreConsequence: 2,
      riskMitigation:
        "International best‐practice safety guidance followed strictly and communicated to market during & postproject",
      riskPostProbability: 2,
      riskPostConsequence: 2,
    },
    {
      riskId: "com14",
      riskType: "commercial",
      category: "sw",
      riskDescription:
        "Complexity of Service Design higher than expectation requiring more resource than planned",
      riskPreProbability: 2,
      riskPreConsequence: 2,
      riskMitigation:
        "Continuous re-estimation of resource required. Feature prioritisation undertaken continuously with stakeholders ensuring only critical elements developed. Additional resource available on short notice",
      riskPostProbability: 2,
      riskPostConsequence: 2,
    },
    {
      riskId: "com15",
      riskType: "commercial",
      category: "sw",
      riskDescription:
        "Customer's IT infrastructure integration too burdensome, inhibiting adoption",
      riskPreProbability: 2,
      riskPreConsequence: 2,
      riskMitigation:
        "Thorough research on users' typical IT systems and security measures. R&D for functionality that best serves customer needs",
      riskPostProbability: 2,
      riskPostConsequence: 2,
    },
    {
      riskId: "com16",
      riskType: "commercial",
      category: "sw",
      riskDescription: "Security concerns limit market recognition and trust",
      riskPreProbability: 2,
      riskPreConsequence: 2,
      riskMitigation:
        "Industry-recognised security accreditations will be obtained and communicated to market post-project. R&D in conjunction with stakeholders, leveraging existing distribution channels to develop trust, build knowledge and facilitate platform development. Audits and external assessment will test system, establish benefits provided to market and validate technology",
      riskPostProbability: 2,
      riskPostConsequence: 2,
    },
    {
      riskId: "com17",
      riskType: "commercial",
      category: "sw",
      riskDescription: "Quality-of-Service does not meet expectations",
      riskPreProbability: 2,
      riskPreConsequence: 2,
      riskMitigation:
        "Regularly monitoring customer feedback and taking proactive measures to ensure expected Quality-of-Service",
      riskPostProbability: 2,
      riskPostConsequence: 2,
    },
    {
      riskId: "com18",
      riskType: "commercial",
      category: "sw",
      riskDescription:
        "Platform cannot cost effectively deliver recognisable added value",
      riskPreProbability: 2,
      riskPreConsequence: 2,
      riskMitigation:
        "R&D in conjuntion with customers to ensure significant added value. Regular review during development to ensure efficiency and cost effectiveness",
      riskPostProbability: 2,
      riskPostConsequence: 2,
    },
    {
      riskId: "com19",
      riskType: "commercial",
      category: "sw",
      riskDescription:
        "Lack of interest/trust results in low levels of engagement",
      riskPreProbability: 2,
      riskPreConsequence: 2,
      riskMitigation:
        "Full social media and digital marketing plan to create maximum impact through project and beyond. Providing incentives for initial adoption (free trials etc) and targeting based on propensity to utilise the technology. Resource dedicated to raising platform profile",
      riskPostProbability: 2,
      riskPostConsequence: 2,
    },
    {
      riskId: "com20",
      riskType: "commercial",
      category: "sw",
      riskDescription: "Users reject novel subscription model",
      riskPreProbability: 2,
      riskPreConsequence: 2,
      riskMitigation:
        "Platform designed for continuous engagment, with relevant content pushed to users to encourage engagement. Developing marketing communication and case studies showing platform utility and benefits increase over time. Free trials of subscription service offered",
      riskPostProbability: 2,
      riskPostConsequence: 2,
    },
    {
      riskId: "com21",
      riskType: "commercial",
      category: "dlt",
      riskDescription:
        "Customers do not trust blockchain can ensure data privacy",
      riskPreProbability: 2,
      riskPreConsequence: 2,
      riskMitigation:
        "Extensive stress testing, offering bounty fees to experts in blockchain community to identify/eliminate bugs. Certified cryptographic primitives as building blocks, world leading security expertise and external audits",
      riskPostProbability: 2,
      riskPostConsequence: 2,
    },
    {
      riskId: "com22",
      riskType: "commercial",
      category: "dat",
      riskDescription:
        "Users are suspicious about data being collected by the platform, limiting market traction and trust",
      riskPreProbability: 2,
      riskPreConsequence: 2,
      riskMitigation:
        "Communication to ensure users are clear their data will be used ethically and for their benefit. Relevant regulations/standards followed and R&D in conjunction with stakeholders to establish market trust and recognition. Outputs will be aggregated/anonymised",
      riskPostProbability: 2,
      riskPostConsequence: 2,
    },
    {
      riskId: "com23",
      riskType: "commercial",
      category: "dat",
      riskDescription:
        "Required real-time data is too expensive, increasing the cost of platform, making it uncompetitive",
      riskPreProbability: 2,
      riskPreConsequence: 2,
      riskMitigation:
        "Existing relationships with data providers and financial modelling by project partners shows real-time data cost will not be prohibitive. Transitioning to in-house real-time data as data collected grows exponentially",
      riskPostProbability: 2,
      riskPostConsequence: 2,
    },
    {
      riskId: "com24",
      riskType: "commercial",
      category: "ai",
      riskDescription: "Poor quality/fit of recommendations damages reputation",
      riskPreProbability: 2,
      riskPreConsequence: 2,
      riskMitigation:
        "Check of potential recommendations by experts before input into recommendation engine. Appropriate disclaimers in contracts. Team's extensive experience will ensure logic of recommendation engine is accurate",
      riskPostProbability: 2,
      riskPostConsequence: 2,
    },
    {
      riskId: "com25",
      riskType: "commercial",
      category: "ui",
      riskDescription:
        "Unable to create relevant tool due to inadequate customer touchpoints during development",
      riskPreProbability: 2,
      riskPreConsequence: 2,
      riskMitigation:
        "Responsive development process will take a modular approach to UI, allowing the generation of multiple UXs per individual feature and testing with a diverse user group to optimise solution",
      riskPostProbability: 2,
      riskPostConsequence: 2,
    },
    {
      riskId: "com26",
      riskType: "commercial",
      category: "man",
      riskDescription:
        "Installation cost is too high to be commercially viable",
      riskPreProbability: 2,
      riskPreConsequence: 2,
      riskMitigation:
        "Testing and commercial assessment during project to establish optimal installation methodology",
      riskPostProbability: 2,
      riskPostConsequence: 2,
    },
    {
      riskId: "com27",
      riskType: "commercial",
      category: "med",
      riskDescription:
        "Market does not trust project’s clinical evidence, leading to difficulty achieving medical approval",
      riskPreProbability: 2,
      riskPreConsequence: 2,
      riskMitigation:
        "Providing incentives for initial adoption (free trials etc) and targeting based on propensity to utilise the technology. Publication of papers on benefits in respected journals. Leveraging existing distribution channels to develop trust, build knowledge and aid platform development",
      riskPostProbability: 2,
      riskPostConsequence: 2,
    },
    {
      riskId: "com28",
      riskType: "commercial",
      category: "med",
      riskDescription: "Unable to achieve MDD/MHRA approval",
      riskPreProbability: 2,
      riskPreConsequence: 2,
      riskMitigation:
        "Liaising with approval org early in project. MHRA will be engaged from project start and will be informed of developments",
      riskPostProbability: 2,
      riskPostConsequence: 2,
    },
    {
      riskId: "com29",
      riskType: "commercial",
      category: "med",
      riskDescription:
        "Health Economics report indicates only marginal benefit of system",
      riskPreProbability: 2,
      riskPreConsequence: 2,
      riskMitigation:
        "Regular review of progress on health economics research with experts to identify issues early and alter strategy if required",
      riskPostProbability: 2,
      riskPostConsequence: 2,
    },
  ],
};

module.exports.roles = roleListObject;
module.exports.tasks = taskListObject;
module.exports.risks = riskTemplateObject;
